import './globals.css'
import { Nunito } from 'next/font/google'
import Header from './components/Header'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'PODCAST APP',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Header />
        <main className=''>{children}</main>
      </body>
    </html>
  )
}
