import Header from './components/Header'
import Provider from './components/Provider'
import './globals.css'

export const metadata = {
	title: 'PODCAST APP',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head>
				<link rel="manifest" href="/manifest.json"/>
				<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
				<link rel="manifest" href="/site.webmanifest"></link>
				<meta name="theme-color" media="(prefers-color-scheme: light)" content="#fff"></meta>
			</head>
			<body className='bg-White'>
				<Provider>
					<Header />
					<main>{children}</main>
				</Provider>
			</body>
		</html>
	)
}
